// https://eslint.org/docs/rules/#possible-problems
const ESLINT_POSSIBLE_ERRORS_RULES = {
	'array-callback-return': ['error', { allowImplicit: true }],
	'constructor-super': 'error',
	'for-direction': 'error',
	'getter-return': 'error',
	'no-async-promise-executor': 'error',
	'no-await-in-loop': 'error',
	'no-class-assign': 'error',
	'no-compare-neg-zero': 'error',
	'no-cond-assign': 'error',
	'no-const-assign': 'error',
	'no-constant-condition': 'error',
	'no-constructor-return': 'error',
	'no-control-regex': 'error',
	'no-debugger': 'error',
	'no-dupe-args': 'error',
	'no-dupe-class-members': 'error',
	'no-dupe-else-if': 'error',
	'no-dupe-keys': 'error',
	'no-duplicate-case': 'error',
	'no-duplicate-imports': 'off',
	'no-empty-character-class': 'error',
	'no-empty-pattern': 'error',
	'no-ex-assign': 'error',
	'no-fallthrough': 'error',
	'no-func-assign': 'error',
	'no-import-assign': 'error',
	'no-inner-declarations': 'error',
	'no-invalid-regexp': 'error',
	'no-irregular-whitespace': 'error',
	'no-loss-of-precision': 'error',
	'no-misleading-character-class': 'error',
	'no-new-symbol': 'error',
	'no-obj-calls': 'error',
	'no-promise-executor-return': 'error',
	'no-prototype-builtins': 'error',
	'no-self-assign': ['error', { props: true }],
	'no-self-compare': 'error',
	'no-setter-return': 'error',
	'no-sparse-arrays': 'error',
	'no-template-curly-in-string': 'error',
	'no-this-before-super': 'error',
	'no-undef': ['error', { typeof: true }],
	'no-unexpected-multiline': 'error',
	'no-unmodified-loop-condition': 'error',
	'no-unreachable': 'error',
	'no-unreachable-loop': 'error',
	'no-unsafe-finally': 'error',
	'no-unsafe-negation': 'error',
	'no-unsafe-optional-chaining': 'error',
	'no-unused-private-class-members': 'error',
	'no-unused-vars': [
		'error',
		{
			vars: 'all',
			args: 'after-used',
			ignoreRestSiblings: true,
			argsIgnorePattern: /^_/.source,
			caughtErrors: 'all',
			caughtErrorsIgnorePattern: /^_$/.source,
		},
	],
	'no-use-before-define': 'off',
	'no-useless-backreference': 'error',
	'require-atomic-updates': 'error',
	'use-isnan': 'error',
	'valid-typeof': ['error', { requireStringLiterals: false }],
};

// https://eslint.org/docs/rules/#suggestions
const ESLINT_SUGGESTIONS_RULES = {
	'accessor-pairs': ['error', { enforceForClassMembers: true }],
	'arrow-body-style': 'off',
	'block-scoped-var': 'error',
	camelcase: ['error', { properties: 'always' }],
	'capitalized-comments': [
		'error',
		'always',
		{
			ignorePattern: /prettier-ignore/.source,
			ignoreInlineComments: true,
			ignoreConsecutiveComments: true,
		},
	],
	'class-methods-use-this': 'off',
	complexity: 'warn',
	'consistent-return': 'off',
	'consistent-this': 'off',
	curly: 'error',
	'default-case': 'error',
	'default-case-last': 'error',
	'default-param-last': 'error',
	'dot-notation': 'error',
	eqeqeq: 'error',
	'func-name-matching': ['error', { considerPropertyDescriptor: true }],
	'func-names': ['error', 'never'],
	'func-style': 'off',
	'grouped-accessor-pairs': ['error', 'getBeforeSet'],
	'guard-for-in': 'error',
	'id-denylist': 'off',
	'id-length': 'off',
	'id-match': 'off',
	'init-declarations': 'off',
	'max-classes-per-file': 'off',
	'max-depth': 'warn',
	'max-lines': 'off',
	'max-lines-per-function': 'off',
	'max-nested-callbacks': ['warn', 4],
	'max-params': ['warn', { max: 4 }],
	'max-statements': 'off',
	'multiline-comment-style': 'off',
	'new-cap': [
		'error',
		{
			newIsCap: true,
			capIsNew: true,
		},
	],
	'no-alert': 'error',
	'no-array-constructor': 'error',
	'no-bitwise': 'error',
	'no-caller': 'error',
	'no-case-declarations': 'error',
	'no-confusing-arrow': 'off',
	'no-console': 'off',
	'no-continue': 'off',
	'no-delete-var': 'error',
	'no-div-regex': 'off',
	'no-else-return': ['error', { allowElseIf: false }],
	'no-empty': ['error', { allowEmptyCatch: true }],
	'no-empty-function': 'off',
	'no-eq-null': 'error',
	'no-eval': 'error',
	'no-extend-native': 'error',
	'no-extra-bind': 'error',
	'no-extra-boolean-cast': 'error',
	'no-extra-label': 'error',
	'no-extra-semi': 'error',
	'no-floating-decimal': 'error',
	'no-global-assign': 'error',
	'no-implicit-coercion': 'error',
	'no-implicit-globals': 'error',
	'no-implied-eval': 'error',
	'no-inline-comments': 'off',
	'no-invalid-this': 'off',
	'no-iterator': 'error',
	'no-label-var': 'error',
	'no-labels': 'error',
	'no-lone-blocks': 'error',
	'no-lonely-if': 'error',
	'no-loop-func': 'error',
	'no-magic-numbers': 'off',
	'no-mixed-operators': 'error',
	'no-multi-assign': 'error',
	'no-multi-str': 'error',
	'no-negated-condition': 'error',
	'no-nested-ternary': 'error',
	'no-new': 'error',
	'no-new-func': 'error',
	'no-new-object': 'error',
	'no-new-wrappers': 'error',
	'no-nonoctal-decimal-escape': 'error',
	'no-octal': 'error',
	'no-octal-escape': 'error',
	'no-param-reassign': 'error',
	'no-plusplus': 'off',
	'no-proto': 'error',
	'no-redeclare': 'error',
	'no-regex-spaces': 'error',
	'no-restricted-exports': 'off',
	'no-restricted-globals': ['error', 'event'],
	'no-restricted-imports': [
		'error',
		'domain',
		'freelist',
		'smalloc',
		'sys',
		'colors',
	],
	'no-restricted-properties': 'off',
	'no-restricted-syntax': ['error', 'WithStatement'],
	'no-return-assign': ['error', 'always'],
	'no-return-await': 'error',
	'no-script-url': 'error',
	'no-sequences': 'error',
	'no-shadow': 'off',
	'no-shadow-restricted-names': 'error',
	'no-ternary': 'off',
	'no-throw-literal': 'error',
	'no-undef-init': 'error',
	'no-undefined': 'off',
	'no-underscore-dangle': 'off',
	'no-unneeded-ternary': 'error',
	'no-unused-expressions': 'error',
	'no-unused-labels': 'error',
	'no-useless-call': 'error',
	'no-useless-catch': 'error',
	'no-useless-computed-key': ['error', { enforceForClassMembers: true }],
	'no-useless-concat': 'error',
	'no-useless-constructor': 'error',
	'no-useless-escape': 'error',
	'no-useless-rename': 'error',
	'no-useless-return': 'error',
	'no-var': 'error',
	'no-void': 'error',
	'no-warning-comments': 'warn',
	'no-with': 'error',
	'object-shorthand': ['error', 'always'],
	'one-var': ['error', 'never'],
	'one-var-declaration-per-line': 'error',
	'operator-assignment': ['error', 'always'],
	'prefer-arrow-callback': ['error', { allowNamedFunctions: true }],
	'prefer-const': ['error', { destructuring: 'all' }],
	'prefer-destructuring': 'off',
	'prefer-exponentiation-operator': 'error',
	'prefer-named-capture-group': 'error',
	'prefer-numeric-literals': 'error',
	'prefer-object-spread': 'error',
	'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
	'prefer-regex-literals': 'error',
	'prefer-rest-params': 'error',
	'prefer-spread': 'error',
	'prefer-template': 'error',
	'quote-props': ['error', 'as-needed'],
	radix: 'error',
	'require-await': 'off',
	'require-unicode-regexp': 'off',
	'require-yield': 'error',
	'sort-imports': 'off',
	'sort-keys': 'off',
	'sort-vars': 'off',
	'spaced-comment': [
		'error',
		'always',
		{
			line: {
				exceptions: ['-', '+', '*'],
				markers: ['!', '/', '=>'],
			},
			block: {
				exceptions: ['-', '+', '*'],
				markers: ['!', '*'],
				balanced: true,
			},
		},
	],
	strict: 'off',
	'symbol-description': 'error',
	'vars-on-top': 'off',
	yoda: 'error',
};

// https://eslint.org/docs/rules/#layout-formatting
const ESLINT_LAYOUT_AND_FORMATTING_RULES = {
	'array-bracket-newline': ['error', 'consistent'],
	'array-bracket-spacing': ['error', 'never'],
	'array-element-newline': ['error', 'consistent'],
	'arrow-parens': ['error', 'always'],
	'arrow-spacing': [
		'error',
		{
			before: true,
			after: true,
		},
	],
	'block-spacing': ['error', 'always'],
	'brace-style': [
		'error',
		'1tbs',
		{ allowSingleLine: false },
	],
	'comma-dangle': ['error', 'always-multiline'],
	'comma-spacing': [
		'error',
		{
			before: false,
			after: true,
		},
	],
	'comma-style': ['error', 'last'],
	'computed-property-spacing': [
		'error',
		'never',
		{ enforceForClassMembers: true },
	],
	'dot-location': ['error', 'property'],
	'eol-last': 'error',
	'func-call-spacing': ['error', 'never'],
	'function-call-argument-newline': ['error', 'consistent'],
	'function-paren-newline': 'off',
	'generator-star-spacing': ['error', 'both'],
	'implicit-arrow-linebreak': 'off',
	indent: [
		'error',
		'tab',
		{ SwitchCase: 1 },
	],
	'jsx-quotes': 'error',
	'key-spacing': [
		'error',
		{
			beforeColon: false,
			afterColon: true,
		},
	],
	'keyword-spacing': 'error',
	'line-comment-position': 'off',
	'linebreak-style': [
		'error',
		'unix',
	],
	'lines-around-comment': 'off',
	'lines-between-class-members': [
		'error',
		'always',
		{ exceptAfterSingleLine: true },
	],
	'max-len': 'off',
	'max-statements-per-line': 'error',
	'multiline-ternary': ['error', 'never'],
	'new-parens': 'error',
	'newline-per-chained-call': 'off',
	'no-extra-parens': 'error',
	'no-mixed-spaces-and-tabs': 'error',
	'no-multi-spaces': 'error',
	'no-multiple-empty-lines': ['error', { max: 1 }],
	'no-tabs': 'off',
	'no-trailing-spaces': 'error',
	'no-whitespace-before-property': 'error',
	'nonblock-statement-body-position': 'off',
	'object-curly-newline': 'off',
	'object-curly-spacing': ['error', 'always'],
	'object-property-newline': 'off',
	'operator-linebreak': ['error', 'after'],
	'padded-blocks': [
		'error',
		'never',
		{ allowSingleLineBlocks: false },
	],
	'padding-line-between-statements': [
		'error',
		{
			blankLine: 'always',
			prev: 'multiline-block-like',
			next: '*',
		},
	],
	quotes: ['error', 'single', { avoidEscape: true }],
	'rest-spread-spacing': ['error', 'never'],
	semi: ['error', 'always'],
	'semi-spacing': [
		'error',
		{
			before: false,
			after: true,
		},
	],
	'semi-style': ['error', 'last'],
	'space-before-blocks': ['error', 'always'],
	'space-before-function-paren': [
		'error',
		{
			anonymous: 'always',
			named: 'never',
			asyncArrow: 'always',
		},
	],
	'space-in-parens': ['error', 'never'],
	'space-infix-ops': 'error',
	'space-unary-ops': 'error',
	'switch-colon-spacing': [
		'error',
		{
			after: true,
			before: false,
		},
	],
	'template-curly-spacing': 'error',
	'template-tag-spacing': ['error', 'never'],
	'unicode-bom': ['error', 'never'],
	'wrap-iife': ['error', 'inside', { functionPrototypeMethods: true }],
	'wrap-regex': 'off',
	'yield-star-spacing': ['error', 'both'],
};

module.exports = {
	...ESLINT_POSSIBLE_ERRORS_RULES,
	...ESLINT_SUGGESTIONS_RULES,
	...ESLINT_LAYOUT_AND_FORMATTING_RULES,
};
