const STYLISTIC_RULES = {
	'@stylistic/array-bracket-newline': ['error', 'consistent'],
	'@stylistic/array-bracket-spacing': ['error', 'never'],
	'@stylistic/array-element-newline': ['error', 'consistent'],
	'@stylistic/arrow-parens': ['error', 'always'],
	'@stylistic/arrow-spacing': [
		'error',
		{
			before: true,
			after: true,
		},
	],
	'@stylistic/block-spacing': ['error', 'always'],
	'@stylistic/brace-style': [
		'error',
		'1tbs',
		{ allowSingleLine: false },
	],
	'@stylistic/comma-dangle': ['error', 'always-multiline'],
	'@stylistic/comma-spacing': [
		'error',
		{
			before: false,
			after: true,
		},
	],
	'@stylistic/comma-style': ['error', 'last'],
	'@stylistic/computed-property-spacing': [
		'error',
		'never',
		{ enforceForClassMembers: true },
	],
	'@stylistic/dot-location': ['error', 'property'],
	'@stylistic/eol-last': 'error',
	'@stylistic/func-call-spacing': ['error', 'never'],
	'@stylistic/function-call-argument-newline': ['error', 'consistent'],
	'@stylistic/function-paren-newline': 'off',
	'@stylistic/generator-star-spacing': ['error', 'both'],
	'@stylistic/implicit-arrow-linebreak': 'off',
	'@stylistic/indent': [
		'error',
		'tab',
		{ SwitchCase: 1 },
	],
	'@stylistic/jsx-quotes': 'error',
	'@stylistic/key-spacing': [
		'error',
		{
			beforeColon: false,
			afterColon: true,
		},
	],
	'@stylistic/keyword-spacing': 'error',
	'@stylistic/linebreak-style': ['error', 'unix'],
	'@stylistic/lines-around-comment': 'off',
	'@stylistic/lines-between-class-members': [
		'error',
		'always',
		{ exceptAfterSingleLine: true },
	],
	'@stylistic/max-len': 'off',
	'@stylistic/max-statements-per-line': 'error',
	'@stylistic/multiline-ternary': ['error', 'never'],
	'@stylistic/new-parens': 'error',
	'@stylistic/newline-per-chained-call': 'off',
	'@stylistic/no-confusing-arrow': 'off',
	'@stylistic/no-extra-parens': 'error',
	'@stylistic/no-extra-semi': 'error',
	'@stylistic/no-floating-decimal': 'error',
	'@stylistic/no-mixed-operators': 'error',
	'@stylistic/no-mixed-spaces-and-tabs': 'error',
	'@stylistic/no-multi-spaces': 'error',
	'@stylistic/no-multiple-empty-lines': ['error', { max: 1 }],
	'@stylistic/no-tabs': 'off',
	'@stylistic/no-trailing-spaces': 'error',
	'@stylistic/no-whitespace-before-property': 'error',
	'@stylistic/nonblock-statement-body-position': 'off',
	'@stylistic/object-curly-newline': 'off',
	'@stylistic/object-curly-spacing': ['error', 'always'],
	'@stylistic/object-property-newline': 'off',
	'@stylistic/one-var-declaration-per-line': 'error',
	'@stylistic/operator-linebreak': ['error', 'after'],
	'@stylistic/padded-blocks': [
		'error',
		'never',
		{ allowSingleLineBlocks: false },
	],
	'@stylistic/padding-line-between-statements': [
		'error',
		{
			blankLine: 'always',
			prev: 'multiline-block-like',
			next: '*',
		},
	],
	'@stylistic/quote-props': ['error', 'as-needed'],
	'@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
	'@stylistic/rest-spread-spacing': ['error', 'never'],
	'@stylistic/semi': ['error', 'always'],
	'@stylistic/semi-spacing': [
		'error',
		{
			before: false,
			after: true,
		},
	],
	'@stylistic/semi-style': ['error', 'last'],
	'@stylistic/space-before-blocks': ['error', 'always'],
	'@stylistic/space-before-function-paren': [
		'error',
		{
			anonymous: 'always',
			named: 'never',
			asyncArrow: 'always',
		},
	],
	'@stylistic/space-in-parens': ['error', 'never'],
	'@stylistic/space-infix-ops': 'error',
	'@stylistic/space-unary-ops': 'error',
	'@stylistic/spaced-comment': [
		'error',
		'always',
		{
			line: {
				exceptions: ['-', '+', '*'],
				markers: ['!', '/', '=>'],
			},
			block: {
				exceptions: ['-', '+', '*'],
				markers: ['!', '*'],
				balanced: true,
			},
		},
	],
	'@stylistic/switch-colon-spacing': [
		'error',
		{
			after: true,
			before: false,
		},
	],
	'@stylistic/template-curly-spacing': 'error',
	'@stylistic/template-tag-spacing': ['error', 'never'],
	'@stylistic/wrap-iife': ['error', 'inside', { functionPrototypeMethods: true }],
	'@stylistic/wrap-regex': 'off',
	'@stylistic/yield-star-spacing': ['error', 'both'],
	'@stylistic/jsx-child-element-spacing': 'off',
	'@stylistic/jsx-closing-bracket-location': 'off',
	'@stylistic/jsx-closing-tag-location': 'off',
	'@stylistic/jsx-curly-brace-presence': 'off',
	'@stylistic/jsx-curly-newline': 'off',
	'@stylistic/jsx-curly-spacing': 'off',
	'@stylistic/jsx-equals-spacing': 'off',
	'@stylistic/jsx-first-prop-new-line': 'off',
	'@stylistic/jsx-indent': 'off',
	'@stylistic/jsx-indent-props': 'off',
	'@stylistic/jsx-max-props-per-line': 'off',
	'@stylistic/jsx-newline': 'off',
	'@stylistic/jsx-one-expression-per-line': 'off',
	'@stylistic/jsx-props-no-multi-spaces': 'off',
	'@stylistic/jsx-self-closing-comp': 'off',
	'@stylistic/jsx-sort-props': 'off',
	'@stylistic/jsx-tag-spacing': 'off',
	'@stylistic/jsx-wrap-multilines': 'off',
	'@stylistic/member-delimiter-style': 'off',
	'@stylistic/type-annotation-spacing': 'off',
};

module.exports = {
	...STYLISTIC_RULES,
};
