name: CI

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: always()
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Bundle sources
        run: npm run build
      - name: Run Hygiene Checks
        run: npm run lint
      - name: Run unit tests
        run: npm run test

  test:
    name: Test on node@${{ matrix.node_version }}
    if: always()
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version: [18.18, 18, 20, 22, 23]
    steps:
      - name: Setup repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install dependencies
        run: npm install
      - name: Bundle sources
        run: npm run build
      - name: Run Hygiene Checks
        run: npm run lint
