name: CI

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Node.js ${{ matrix.node_version }} on ${{ matrix.os }}
    if: always()
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: [10, 12, 14, 15]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install dependencies
        run: npm install
      - name: Bundle sources
        run: npm run build
      - name: Run Hygiene Checks
        run: npm run lint
      - name: Run unit tests
        run: npm run test
